### ISSUE TITLE
Difficulty Accessing Table Content in Textract Output

### ISSUE THREAD

**Issue by rossanodr** [ScribeLabsAI/amazon-trp-node#35]
I'm aware that this question may seem rather basic, but I'm facing an issue with accessing the complete content of tables in my code. In the example below, the `console.log("p", p.text)` successfully displays all the content of the image. However, `console.log("c.text", c.text)` appears to access only some elements. Could someone provide an example of how to iterate over the table properly?

```
const params = {
  Document: {
    Bytes: blob,
  },
  FeatureTypes: ["TABLES"],
};

const command = new AnalyzeDocumentCommand(params);
try {
  const data = await textractClient.send(command);

  const doc = new Document(data.Blocks as BlockStruct[]);
  doc.pages.forEach((p) => {
    console.log("p", p.text);
    p.tables.forEach((t) => {
      t.rows.forEach((l) => {
        console.log("l", l.cells);
        l.cells.forEach((c) => {
          console.log("c.text", c.text);
        });
      });
    });
  });
}
I'm looking for assistance in understanding why c.text is not accessing the entire content and how to properly iterate over the table to access all its elements. Any insights or examples would be greatly appreciated.

Tahnks its not easy to be a noob

**Comment by EHadoux** [comment]
Hey, I don't think anything is wrong with your code but I suspect the difference you see in `p.text` v. `c.text` is due to everything that's on the page (displayed in the former) and but not detected as part of a table (so ignored in the more nested loops). 
What do you see when you feed the document manually in the Textract console (on this page)? In the tables tab you'll see what Textract thinks is part of a table and what is not.

![image](https://github.com/ScribeLabsAI/amazon-trp-node/assets/1655646/1005214b-28e0-4b59-9746-5934c46453e7)
